# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67ed05e3108096348f13d55989d5c3b8121ab9a85b17b627634e3a353a3bd1e02a03005a61a32ed64df2c351e58cf9eefdf6beea726d2a55d7363c6c0e8aebd3

test:
  secret_key_base: e5c0e1de099c503185be530a374a567cdab887ef2f7f51bc565fbc5ba90e4f9da739ddb0277be082801f4b34659a6bab7fdeb2d5ffb9823c1ef858ab53065950

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
